### ISSUE TITLE
Wrong condition in picoboard/blinky

### ISSUE THREAD

**Issue by hotovson** [raspberrypi/pico-examples#86]
there is wrong condition on lines
https://github.com/raspberrypi/pico-examples/blob/2fb08a028f886624ebc9c938775e054860549159/picoboard/blinky/blinky.c#L57
and
https://github.com/raspberrypi/pico-examples/blob/2fb08a028f886624ebc9c938775e054860549159/picoboard/blinky/blinky.c#L59

must be 
`if (*str >= 'A' && *str <= 'Z') {` 
and 
`} else if (*str >= 'a' && *str <= 'z') {`
respectively

**Comment by lurch** [comment]
Hah, just took me about 10 minutes to see what the difference was!! :laughing: :mag: 
In the version at https://github.com/raspberrypi/pico-examples/blob/develop/picoboard/blinky/blinky.c it's using `< 'z'` but it should be `<= 'z'` - which we obviously didn't notice ourselves because the example `"Hello world"` string doesn't contain a `z`.
Thanks for spotting this, I'll submit a PR...

**Comment by lurch** [comment]
This can be closed now @kilograham

**Comment by lurch** [comment]
@kilograham Ahhhh, so [this](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) is why issues aren't being closed when the associated PR is merged:
> Note: The special keywords in a pull request description are interpreted when the pull request targets the repository's default branch. However, if the PR's base is any other branch, then these keywords are ignored, no links are created and merging the PR has no effect on the issues.

Looks like there's a 3rd-party "action" to get around that, if this behaviour becomes too annoying https://github.com/marketplace/actions/closes-issues-related-to-a-merged-pull-request
(but I dunno the security implications of giving a 3rd-party addon access to `secrets.GITHUB_TOKEN` )
